FROM apache/airflow:3.3.1

USER root
# Static Docker CLI so DAG tasks can `docker run` pipeline + dbt images via the mounted socket.
RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-27.5.1.tgz \
    | tar -xz -C /tmp \
    && mv /tmp/docker/docker /usr/local/bin/docker \
    && rm -rf /tmp/docker \
    && chmod +x /usr/local/bin/docker

USER airflow
